// This file is autogenerated by the hyperschema compiler
// Schema Version: 2
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 2

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @gip/repos
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.buffer.preencode(state, m.key)
    state.end++ // flags are fixed size

    if (m.description) c.string.preencode(state, m.description)
    if (m.lastPushed) c.uint.preencode(state, m.lastPushed)
  },
  encode(state, m) {
    const flags = (m.description ? 1 : 0) | (m.lastPushed ? 2 : 0)

    c.string.encode(state, m.name)
    c.buffer.encode(state, m.key)
    c.uint8.encode(state, flags)

    if (m.description) c.string.encode(state, m.description)
    if (m.lastPushed) c.uint.encode(state, m.lastPushed)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const flags = c.uint8.decode(state)

    return {
      name: r0,
      key: r1,
      description: (flags & 1) !== 0 ? c.string.decode(state) : null,
      lastPushed: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @gip/config.blindPeers
const encoding1_0 = c.array(c.fixed32)

// @gip/config
const encoding1 = {
  preencode(state, m) {
    state.end++ // flags are fixed size

    if (version >= 2 && m.blindPeers) encoding1_0.preencode(state, m.blindPeers)
  },
  encode(state, m) {
    const flags = (version >= 2 && m.blindPeers) ? 1 : 0

    c.uint8.encode(state, flags)

    if (version >= 2 && m.blindPeers) encoding1_0.encode(state, m.blindPeers)
  },
  decode(state) {
    const flags = c.uint8.decode(state)

    return {
      blindPeers: (version >= 2 && (flags & 1) !== 0) ? encoding1_0.decode(state) : null
    }
  }
}

// @gip/repos/hyperdb#0
const encoding2 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
    state.end++ // flags are fixed size

    if (m.description) c.string.preencode(state, m.description)
    if (m.lastPushed) c.uint.preencode(state, m.lastPushed)
  },
  encode(state, m) {
    const flags = (m.description ? 1 : 0) | (m.lastPushed ? 2 : 0)

    c.buffer.encode(state, m.key)
    c.uint8.encode(state, flags)

    if (m.description) c.string.encode(state, m.description)
    if (m.lastPushed) c.uint.encode(state, m.lastPushed)
  },
  decode(state) {
    const r1 = c.buffer.decode(state)
    const flags = c.uint8.decode(state)

    return {
      name: null,
      key: r1,
      description: (flags & 1) !== 0 ? c.string.decode(state) : null,
      lastPushed: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@gip/repos':
      return encoding0
    case '@gip/config':
      return encoding1
    case '@gip/repos/hyperdb#0':
      return encoding2
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
